import cx_Freeze

executables = [cx_Freeze.Executable("main.py")]

cx_Freeze.setup(
    name="Math Game",
    options={"build_exe": {"packages": ["pygame"],
                           "include_files": [("sound_files/begin_digits.wav", "sound_files/begin_digits.wav"),
                                             ("sound_files/count_0_to_10.wav", "sound_files/count_0_to_10.wav"),
                                             ("sound_files/find_number.wav", "sound_files/find_number.wav"),
                                             ("sound_files/find_the_digit.wav", "sound_files/find_the_digit.wav"),
                                             ("sound_files/found_digit.wav", "sound_files/found_digit.wav"),
                                             ("sound_files/found_number.wav", "sound_files/found_number.wav"),
                                             ("sound_files/intro.wav", "sound_files/intro.wav"),
                                             ("sound_files/not_right.wav", "sound_files/not_right.wav"),
                                             ("sound_files/numbers_from_digits.wav", "sound_files/numbers_from_digits.wav"),
                                             ("sound_files/only_10_digits.wav", "sound_files/only_10_digits.wav"),
                                             ("sound_files/rec_digits_learn_count.wav", "sound_files/rec_digits_learn_count.wav"),
                                             ("sound_files/say_together.wav", "sound_files/say_together.wav"),
                                             ("sound_files/try_again.wav", "sound_files/try_again.wav"),
                                             ("sound_files/very_good.wav", "sound_files/very_good.wav"),
                                             ("sound_files/the_number.wav", "sound_files/the_number.wav"),
                                             ("sound_files/looks_like.wav", "sound_files/looks_like.wav"),
                                             ("sound_files/button.wav", "sound_files/button.wav"),
                                             ("sound_files/click_the.wav", "sound_files/click_the.wav"),
                                             ("sound_files/for_letters.wav", "sound_files/for_letters.wav"),
                                             ("sound_files/for_numbers.wav", "sound_files/for_numbers.wav"),
                                             ("sound_files/numbers_or_letters.wav", "sound_files/numbers_or_letters.wav"),
                                             ("sound_files/colors/blue.wav", "sound_files/colors/blue.wav"),
                                             ("sound_files/colors/green.wav", "sound_files/colors/green.wav"),
                                             ("sound_files/colors/orange.wav", "sound_files/colors/orange.wav"),
                                             ("sound_files/colors/purple.wav", "sound_files/colors/purple.wav"),
                                             ("sound_files/colors/red.wav", "sound_files/colors/red.wav"),
                                             ("sound_files/colors/yellow.wav", "sound_files/colors/yellow.wav"),
                                             ("sound_files/numbers/zero.wav", "sound_files/numbers/zero.wav"),
                                             ("sound_files/numbers/one.wav", "sound_files/numbers/one.wav"),
                                             ("sound_files/numbers/two.wav", "sound_files/numbers/two.wav"),
                                             ("sound_files/numbers/three.wav", "sound_files/numbers/three.wav"),
                                             ("sound_files/numbers/four.wav", "sound_files/numbers/four.wav"),
                                             ("sound_files/numbers/five.wav", "sound_files/numbers/five.wav"),
                                             ("sound_files/numbers/five.wav", "sound_files/numbers/five.wav"),
                                             ("sound_files/numbers/six.wav", "sound_files/numbers/six.wav"),
                                             ("sound_files/numbers/seven.wav", "sound_files/numbers/seven.wav"),
                                             ("sound_files/numbers/eight.wav", "sound_files/numbers/eight.wav"),
                                             ("sound_files/numbers/nine.wav", "sound_files/numbers/nine.wav"),
                                             ("sound_files/numbers/ten.wav", "sound_files/numbers/ten.wav"),
                                             ("sound_files/numbers/eleven.wav", "sound_files/numbers/eleven.wav"),
                                             ("sound_files/numbers/twelve.wav", "sound_files/numbers/twelve.wav"),
                                             ("sound_files/numbers/thirteen.wav", "sound_files/numbers/thirteen.wav"),
                                             ("sound_files/numbers/fourteen.wav", "sound_files/numbers/fourteen.wav"),
                                             ("sound_files/numbers/fifteen.wav", "sound_files/numbers/fifteen.wav"),
                                             ("sound_files/numbers/sixteen.wav", "sound_files/numbers/sixteen.wav"),
                                             ("sound_files/numbers/seventeen.wav", "sound_files/numbers/seventeen.wav"),
                                             ("sound_files/numbers/eighteen.wav", "sound_files/numbers/eighteen.wav"),
                                             ("sound_files/numbers/nineteen.wav", "sound_files/numbers/nineteen.wav"),
                                             ("sound_files/numbers/twenty.wav", "sound_files/numbers/twenty.wav"),
                                             ("images/numbers_highlight.png", "images/numbers_highlight.png"),
                                             ("images/spritesheet_numbers_plain.png", "images/spritesheet_numbers_plain.png"),
                                             ("sound_files/alphabet/begin_sing.wav", "sound_files/alphabet/begin_sing.wav"),
                                             ("sound_files/alphabet/find_letter.wav", "sound_files/alphabet/find_letter.wav"),
                                             ("sound_files/alphabet/learn_alphabet.wav", "sound_files/alphabet/learn_alphabet.wav"),
                                             ("sound_files/alphabet/sing_alphabet.wav", "sound_files/alphabet/sing_alphabet.wav"),
                                             ("sound_files/alphabet/alphabet_song.wav", "sound_files/alphabet/alphabet_song.wav"),
                                             ("sound_files/alphabet/letter/a.wav", "sound_files/alphabet/letter/a.wav"),
                                             ("sound_files/alphabet/letter/b.wav", "sound_files/alphabet/letter/b.wav"),
                                             ("sound_files/alphabet/letter/c.wav", "sound_files/alphabet/letter/c.wav"),
                                             ("sound_files/alphabet/letter/d.wav", "sound_files/alphabet/letter/d.wav"),
                                             ("sound_files/alphabet/letter/e.wav", "sound_files/alphabet/letter/e.wav"),
                                             ("sound_files/alphabet/letter/f.wav", "sound_files/alphabet/letter/f.wav"),
                                             ("sound_files/alphabet/letter/g.wav", "sound_files/alphabet/letter/g.wav"),
                                             ("sound_files/alphabet/letter/h.wav", "sound_files/alphabet/letter/h.wav"),
                                             ("sound_files/alphabet/letter/i.wav", "sound_files/alphabet/letter/i.wav"),
                                             ("sound_files/alphabet/letter/j.wav", "sound_files/alphabet/letter/j.wav"),
                                             ("sound_files/alphabet/letter/k.wav", "sound_files/alphabet/letter/k.wav"),
                                             ("sound_files/alphabet/letter/l.wav", "sound_files/alphabet/letter/l.wav"),
                                             ("sound_files/alphabet/letter/m.wav", "sound_files/alphabet/letter/m.wav"),
                                             ("sound_files/alphabet/letter/n.wav", "sound_files/alphabet/letter/n.wav"),
                                             ("sound_files/alphabet/letter/o.wav", "sound_files/alphabet/letter/o.wav"),
                                             ("sound_files/alphabet/letter/p.wav", "sound_files/alphabet/letter/p.wav"),
                                             ("sound_files/alphabet/letter/q.wav", "sound_files/alphabet/letter/q.wav"),
                                             ("sound_files/alphabet/letter/r.wav", "sound_files/alphabet/letter/r.wav"),
                                             ("sound_files/alphabet/letter/s.wav", "sound_files/alphabet/letter/s.wav"),
                                             ("sound_files/alphabet/letter/t.wav", "sound_files/alphabet/letter/t.wav"),
                                             ("sound_files/alphabet/letter/u.wav", "sound_files/alphabet/letter/u.wav"),
                                             ("sound_files/alphabet/letter/v.wav", "sound_files/alphabet/letter/v.wav"),
                                             ("sound_files/alphabet/letter/w.wav", "sound_files/alphabet/letter/w.wav"),
                                             ("sound_files/alphabet/letter/x.wav", "sound_files/alphabet/letter/x.wav"),
                                             ("sound_files/alphabet/letter/y.wav", "sound_files/alphabet/letter/y.wav"),
                                             ("sound_files/alphabet/letter/z.wav", "sound_files/alphabet/letter/z.wav")]}},
    executables=executables
)


